{"name": "Авторизация курьера — проверка ошибок", "status": "failed", "statusDetails": {"message": "AssertionError: assert 504 == 400\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests.test_login_courier.TestCourierLogin object at 0x000001D905932330>, courier_api = <api.courier_api.CourierApi object at 0x000001D905912D50>\ndescription = 'Без пароля', creds = {'login': 'login_user_456'}, expected_status = 400, expected_message = 'Недостаточно данных для входа'\n\n    @pytest.mark.parametrize(\n        \"description, creds, expected_status, expected_message\",\n        [\n            (\"Неправильный логин\",\n             {\"login\": \"wrong_login\", \"password\": CreateCourierData.LOGIN_COURIER[\"password\"]},\n             404, \"Учетная запись не найдена\"),\n    \n            (\"Неправильный пароль\",\n             {\"login\": CreateCourierData.LOGIN_COURIER[\"login\"], \"password\": \"wrong_pass\"},\n             404, \"Учетная запись не найдена\"),\n    \n            (\"Без логина\",\n             {\"password\": CreateCourierData.LOGIN_COURIER[\"password\"]},\n             400, \"Недостаточно данных для входа\"),\n    \n            (\"Без пароля\",\n             {\"login\": CreateCourierData.LOGIN_COURIER[\"login\"]},\n             400, \"Недостаточно данных для входа\"),\n    \n            (\"Несуществующий пользователь\",\n             {\"login\": CreateCourierData.NON_EXISTENT_USER[\"login\"],\n              \"password\": CreateCourierData.NON_EXISTENT_USER[\"password\"]},\n             404, \"Учетная запись не найдена\")\n        ])\n    @allure.title(\"Авторизация курьера — проверка ошибок\")\n    @allure.description(\"Проверка авторизации негативными сценариями\")\n    def test_login_errors(self, courier_api, description, creds, expected_status, expected_message):\n        with allure.step(f\"Сценарий: {description}\"):\n            response = courier_api.login_courier(creds)\n    \n        with allure.step(\"Проверить код ответа\"):\n>           assert response.status_code == expected_status\nE           assert 504 == 400\nE            +  where 504 = <Response [504]>.status_code\n\ntests\\test_login_courier.py:54: AssertionError"}, "description": "Проверка авторизации негативными сценариями", "steps": [{"name": "Сценарий: Без пароля", "status": "passed", "start": 1757417796381, "stop": 1757417856978}, {"name": "Проверить код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 504 == 400\n +  where 504 = <Response [504]>.status_code\n", "trace": "  File \"C:\\Users\\rokst\\PycharmProjects\\Sprint_7\\tests\\test_login_courier.py\", line 54, in test_login_errors\n    assert response.status_code == expected_status\n"}, "start": 1757417856978, "stop": 1757417856978}], "parameters": [{"name": "description", "value": "'Без пароля'"}, {"name": "creds", "value": "{'login': 'login_user_456'}"}, {"name": "expected_status", "value": "400"}, {"name": "expected_message", "value": "'Недостаточно данных для входа'"}], "start": 1757417796381, "stop": 1757417856979, "uuid": "3b10e6b8-82c4-45ed-826e-e473d1b98543", "historyId": "a05fd1be4989a5b21e60a07031c55a14", "testCaseId": "19c43b3cacae3758579e377968a7e303", "fullName": "tests.test_login_courier.TestCourierLogin#test_login_errors", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Ksu"}, {"name": "thread", "value": "14304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestCourierLogin"]}